services:
  slider-captcha:
    build: .
    image: slider-captcha:latest
    container_name: slider-captcha-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - SERVER_WORKERS=4
      - PUZZLE_GENERATOR_CONCURRENCY=4
      - PUZZLE_CACHE_PREFILL=12
      - PUZZLE_CACHE_MAX=48
      - PUZZLE_PREFILL_DIMENSIONS=500x300,400x200
      - IMMEDIATE_CACHE_CLEANUP=false